### PR TITLE
Add docker files

### LINKED ISSUE #24: Have you ever tested the `Dockerfile`?
Problem:
```
Step 19/22 : RUN gulp all
 ---> Running in 7b5af99f7b62
[04:12:29] Local gulp not found in /usr/src/app
[04:12:29] Try running: npm install gulp
The command '/bin/sh -c /usr/local/bin/gulp all' returned a non-zero code: 1
ERROR: Job failed: Process exited with: 1. Reason was:  ()
```
Solution:
```
RUN npm install --save-dev gulp
```

Next problem:
```
$ gulp all
module.js:472
    throw err;
    ^

Error: Cannot find module 'gulp-sass'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/src/app/Gulpfile.js:2:12)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

Solution:

```
npm install gulp-sass
```

Next Problem:
```
$ gulp all
module.js:472
    throw err;
    ^

Error: Cannot find module 'gulp-concat'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/src/app/Gulpfile.js:3:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

Solution
```
npm install gulp-concat
```

Next problem:
```
$gulp all
[07:52:22] Using gulpfile /usr/src/app/Gulpfile.js
[07:52:22] Task 'all' is not in your gulpfile
[07:52:22] Please check the documentation for proper gulpfile formatting
```

Are you kidding me???

### PR DESCRIPTION
**Pull request by fkohrt**
Added `Dockerfile` and `docker-compose.yml`. Now one can get a head start with

- `git clone https://github.com/spacedeck/spacedeck-open`
- configure `config/default.json` (no trailing `/` for the `endpoint`)
- configure `volumes` section inside `docker-compose.yml`:
  - point to existing local file `database.sqlite`
  - point to existing local folder `storage/`, which can be empty, though
- `cd spacedeck-open`
- `sudo docker-compose up -d`

App listens at port ~~`80`~~ `9666`.

If no  `database.sqlite` exists--e. g. when running for the first time--, one first has to create it:

- comment out the whole `volumes` section inside `docker-compose.yml` with `#`
- `sudo docker-compose up -d`
- `sudo docker cp spacedeck:/app/database.sqlite .`
- move `database.sqlite` to an appropriate location
- uncomment the volumes section and point to that location

Alternatively, just comment out the whole `volumes` section and have no persistent storage. All changes will be lost when the container stops (e. g. through `sudo docker-compose down`).

Stop the container with `sudo docker-compose down`. Update the code with `git pull`. After updates or other code changes, start with `sudo docker-compose up -d --build`.

Also, closes #24. What's more, (a) I haven't fully replicated the features of the [Dockerfile](https://github.com/spacedeck/docker-baseimage/blob/1f8fbf5/Dockerfile) over at [spacedeck/docker-baseimage](https://github.com/spacedeck/docker-baseimage), which bases on Debian, and (b) this `docker-compose.yml` could also use volumes instead of bind mounts (in this case, one should not do `sudo docker-compose down` which removes all volumes, `sudo docker-compose stop` is enough).

### CODE REVIEW

**Comment by fkohrt** [comment]
Following up on looking at the existing [Debian Dockerfile](https://github.com/spacedeck/docker-baseimage/blob/1f8fbf5/Dockerfile), a few things remain unclear to me:

1. I am wondering whether choosing the package `ffmpeg-dev` instead of `ffmpeg` adds some other codecs (the Debian Dockerfile uses libav to add some codecs). Or are there any other codec-related packages to be installed?
2. Thumbnail generation does not work with the current setup (see the following log), but #45 doesn't help here, because simply installing the `fontconfig` package doesn't do the trick in Alpine. What is this `Dockerfile` missing? (The Debian Dockerfile does install `libfreetype6`, but installing the Alpine `freetype` package also doesn't solve this.)
3. Is it necessary to install PhantomJS manually, as apparently does the Debian Dockerfile?
4. Am I missing some other Alpine packages that Spacedeck might like (i. e. to support some optional feature)?

```
spacedeck    | [2020-05-11T01:07:29.751Z] Executing (default): SELECT `_id`, `name`, `space_type`, `creator_id`, `parent_space_id`, `access_mode`, `password`, `edit_hash`, `edit_slug`, `editors_locking`, `thumbnail_uri`, `width`, `height`, `background_color`, `background_uri`, `created_at`, `updated_at`, `thumbnail_url`, `thumbnail_updated_at`, `createdAt`, `updatedAt` FROM `spaces` AS `space` WHERE `space`.`_id` = '2142e4ce-adfa-4891-a506-84a50f0e727d';
spacedeck    | [2020-05-11T01:07:29.754Z] [space-screenshot] url: http://<domain>/api/spaces/2142e4ce-adfa-4891-a506-84a50f0e727d/html?api_token=very_secret_phantom_password
spacedeck    | [2020-05-11T01:07:29.754Z] [space-screenshot] export_path: /tmp/2142e4ce-adfa-4891-a506-84a50f0e727d.png
spacedeck    | [2020-05-11T01:07:29.760Z] Executing (default): UPDATE `spaces` SET `thumbnail_updated_at`='2020-05-11 01:07:29.753 +00:00',`updatedAt`='2020-05-11 01:07:29.753 +00:00' WHERE `_id` = '2142e4ce-adfa-4891-a506-84a50f0e727d'
spacedeck    | [2020-05-11T01:07:29.761Z] { Error: spawn /app/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs ENOENT
spacedeck    |     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
spacedeck    |     at onErrorNT (internal/child_process.js:415:16)
spacedeck    |     at process._tickCallback (internal/process/next_tick.js:63:19)
spacedeck    |   errno: 'ENOENT',
spacedeck    |   code: 'ENOENT',
spacedeck    |   syscall:
spacedeck    |    'spawn /app/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs',
spacedeck    |   path:
spacedeck    |    '/app/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs',
spacedeck    |   spawnargs: [ '/app/node_modules/node-phantom-simple/bridge.js' ] }
```

**Comment by mntmn** [comment]
Hi, thanks for this, highly appreciated. I will look into the phantomjs stuff as soon as I find the time.

**Comment by j6k4m8** [comment]
Hate to be That Random Guy On GitHub With Opinions About Your Pull Request, but it doesn't look like you are using any of the super bleeding-edge features in the docker-compose; might make sense to roll the `version` back (from 2.7) by a few minors so that users don't need to upgrade/change their compose binary to get this to work. 

In exchange for my unsolicited opinion, I'll try to spend some time debugging this too — just pulled the code down to play :)

**Comment by fkohrt** [comment]
@j6k4m8 No, that's totally appreciated! I admit I was too lazy to check for the minimal required version ;)

But that missing thumbnail generation bugs me, so if you find anything with regard to (2)... might also be related to (3).

And ad (1), [this page](https://pkgs.alpinelinux.org/contents?branch=edge&name=ffmpeg-dev&arch=x86&repo=community) says `libavcodec` is included in `ffmpeg-dev`, so I now use that.

**Comment by j6k4m8** [comment]
The only trouble I ran into was the same thing you've documented w.r.t the sqlite database (your docs fix my problem!). You can also just `touch database.sqlite` first and then leave the `volume` section in on first deploy :)

**Comment by fkohrt** [comment]
Good to know! I still want to add some documentation to the README and will include that.

**Comment by fkohrt** [comment]
The [Docker and Node.js Best Practices](https://github.com/nodejs/docker-node/blob/master/docs/BestPractices.md) suggest setting `NODE_ENV=production` and using a non-root `USER node`, but both doesn't work for me (fails due to missing files and wrong permissions).

**Comment by philjak** [comment]
@fkohrt @j6k4m8 The problem of creating previews still exists, right? I cant find any other issue for this particular problem, but this one is closed already. 

> ```
> spacedeck    | [2020-05-11T01:07:29.751Z] Executing (default): SELECT `_id`, `name`, `space_type`, `creator_id`, `parent_space_id`, `access_mode`, `password`, `edit_hash`, `edit_slug`, `editors_locking`, `thumbnail_uri`, `width`, `height`, `background_color`, `background_uri`, `created_at`, `updated_at`, `thumbnail_url`, `thumbnail_updated_at`, `createdAt`, `updatedAt` FROM `spaces` AS `space` WHERE `space`.`_id` = '2142e4ce-adfa-4891-a506-84a50f0e727d';
> spacedeck    | [2020-05-11T01:07:29.754Z] [space-screenshot] url: http://<domain>/api/spaces/2142e4ce-adfa-4891-a506-84a50f0e727d/html?api_token=very_secret_phantom_password
> spacedeck    | [2020-05-11T01:07:29.754Z] [space-screenshot] export_path: /tmp/2142e4ce-adfa-4891-a506-84a50f0e727d.png
> spacedeck    | [2020-05-11T01:07:29.760Z] Executing (default): UPDATE `spaces` SET `thumbnail_updated_at`='2020-05-11 01:07:29.753 +00:00',`updatedAt`='2020-05-11 01:07:29.753 +00:00' WHERE `_id` = '2142e4ce-adfa-4891-a506-84a50f0e727d'
> spacedeck    | [2020-05-11T01:07:29.761Z] { Error: spawn /app/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs ENOENT
> spacedeck    |     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
> spacedeck    |     at onErrorNT (internal/child_process.js:415:16)
> spacedeck    |     at process._tickCallback (internal/process/next_tick.js:63:19)
> spacedeck    |   errno: 'ENOENT',
> spacedeck    |   code: 'ENOENT',
> spacedeck    |   syscall:
> spacedeck    |    'spawn /app/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs',
> spacedeck    |   path:
> spacedeck    |    '/app/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs',
> spacedeck    |   spawnargs: [ '/app/node_modules/node-phantom-simple/bridge.js' ] }
> ```

**Comment by fkohrt** [comment]
> The problem of creating previews still exists, right?

Yeah, I haven't been able to find a solution and the docker file has been merged nevertheless. However I was documenting my attempts to make previews work [above](https://github.com/spacedeck/spacedeck-open/pull/55#issuecomment-626416228), so maybe you can build on that? I believe it has something to do with missing packages, because it does work with the old Debian Dockerfile; but my knowledge of phantom and Alpine is very limited so I couldn't come up with a solution.

**Comment by fkohrt** [comment]
@philjak it was [suggested](https://github.com/spacedeck/spacedeck-open/issues/45#issuecomment-721270349) that we will have to use the Debian based Docker image to make it work. I will eventually look into that and submit a pull request, but anybody feel free to tackle this before me.

**Comment by fkohrt** [comment]
@philjak This has been fixed with #169, by replacing phantomjs with puppeteer.

**Pull request merged**
