### PR TITLE
fix div positionning on Firefox and Safari issue #87

### PR DESCRIPTION
**Pull request by rds13**
This code change should fix issue #87.
It seems the mis-alignement of svg component is induiced by line-height style set on HTML body.

### CODE REVIEW

**Comment by rds13** [comment]
@mntmn any comments ?

**Comment by mntmn** [comment]
Thanks and sorry for my late response. Could this be added to the .artifact class in CSS?

**Comment by rds13** [comment]
@mntmn I've updated the MR and sucessfully test it.

**Comment by rds13** [comment]
@mntmn Can you confirm it's ok ?

**Comment by mntmn** [comment]
Thanks, sorry for the delay!

**Pull request merged**
