### PR TITLE
Create hu.js

### PR DESCRIPTION
**Pull request by ovari**
What does `canel` mean?
https://github.com/spacedeck/spacedeck-open/blob/mnt/locales/en.js#L231
Is it meant to be `cancel`?

Does some other file need to be updated to make the `hu` locale available?

Thank you

### CODE REVIEW

**Comment by ovari** [comment]
@banglashi are you able to accept this pull request? Thank you

**Comment by banglashi** [comment]
Hi @ovari 
yes, there are some other parts that need to be changed in order to include a new locale. I will check and let you know

**Comment by banglashi** [comment]
Hi @ovari 
what would be the proper name for Hungarian in Hungarian for selecting the language?

**Comment by ovari** [comment]
> what would be the proper name for Hungarian in Hungarian for selecting the language?

`magyar`

**Comment by ovari** [comment]
Thanks. A few items from https://github.com/spacedeck/spacedeck-open/commit/9018a233a1d6af4ed747951ac9a9a0bc99de96f2:
* `magyar` starts with a lowercase letter
* Should the locales at line 36 in spacedeck.js be in alphabetical order?
* Should the locales at lines 79 to 88 in views/spacedeck.ejs be in alphabetical order?

What do you think?

Thank you

**Comment by banglashi** [comment]
1. I put it capitalized, because all other languages are. Should I change it?
2. sure, let's be politically correct ;)
3. Will do it here too and even check if we can omit loading non-used languages

**Pull request merged**
