### PR TITLE
Fix to issue #71 Cursor positions on shared whiteboards are inconsistent

### PR DESCRIPTION
**Pull request by MishkinBerteig**
The translation from absolute window coordinates to the coordinates of the virtual space was not being done correctly.

There were a few minor dependencies which _relied on the incorrect calculations_ so I had to fix those references as well.

The key changes are in the file [public/javascripts/spacedeck_whiteboard.js](https://github.com/spacedeck/spacedeck-open/blob/mnt/public/javascripts/spacedeck_whiteboard.js) in the `cursor_point_to_space` method. The original version of the method looks like this:

```
cursor_point_to_space: function(evt) {
  var $scope = this.vm.$root;
  var offset = {left: 0, top: 0};

  evt = fixup_touches(evt);

  return {
    x: (parseInt(evt.pageX) - parseInt(offset.left) - $scope.bounds_margin_horiz) / this.space_zoom,
    y: (parseInt(evt.pageY) - parseInt(offset.top) - $scope.bounds_margin_vert)   / this.space_zoom
  };
},
```
After changes it looks like this… pretty similar, really:

```
cursor_point_to_space: function(evt) {
  var $scope = this.vm.$root;

  evt = fixup_touches(evt);

  return {
    x: $scope.scroll_left + (parseInt(evt.pageX) - $scope.bounds_margin_horiz) / $scope.viewport_zoom,
    y: $scope.scroll_top  + (parseInt(evt.pageY) - $scope.bounds_margin_vert)  / $scope.viewport_zoom
  };
},
```
Basically, the zoom info wasn’t being obtained from the correct place and the scroll offset was being ignored.

There were actually a bunch of other places in that file that needed to be changed because there were several references to the `cursor_point_to_space` method. There was another method also used called `offset_point_in_wrapper` that was related, but I removed the need for it and deleted the method. And finally, there was a small change to the [views/partials/space.html](https://github.com/spacedeck/spacedeck-open/blob/mnt/views/partials/space.html) file related to the whiteboard to put the “lasso” div in the same frame of reference as all the objects on the whiteboard so that it didn’t need any special calculation handling for mouse coordinates.

Finally, I cleaned up two console.log statements in [public/javascripts/spacedeck_sections.js](https://github.com/spacedeck/spacedeck-open/blob/mnt/public/javascripts/spacedeck_sections.js).

### CODE REVIEW

**Comment by MishkinBerteig** [comment]
@mntmn @yrammos Ideally this would be tested by someone else before merging.  I'm a little leery of this as it is a more complex set of changes.  Without automated unit tests, it's hard to know if I've accidentally broken something!  I've done a bunch of manual testing, but...

**Comment by mntmn** [comment]
@MishkinBerteig good work so far, thank you. I'll test it ASAP and give more feedback.

**Comment by mntmn** [comment]
Coordinate translation seems to be fine for tools and everything, but unfortunately panning (middle mouse drag / hold down space and drag) does not work correctly for me:

http://dump.mntmn.com/spacedeck_pr86_glitch.mp4

I mean, it does scroll, but it quickly oscillates between two offsets while doing so. Is this not happening for you?

**Comment by MishkinBerteig** [comment]
@mntmn Good catch.  As well, the board does not actually follow the mouse cursor... it's moving at about half speed.  I'll look into this now.

**Comment by MishkinBerteig** [comment]
@mntmn I just fixed it... again, independent testing would be welcome.  Scrolling is now smooth again.  This fix was really simple.

**Comment by yrammos** [comment]
@MishkinBerteig just tested; confirming the panning patch works as intended. Will continue testing and report any issues. Thanks.

**Comment by MishkinBerteig** [comment]
@mntmn Ping... just checking if this will be accepted or not. I would like to move on to more fixes, but I am waiting on this one to be accepted to make sure that I am building on a "known good" version.  If it cannot be accepted for some reason, please let me know and I will do my utmost to make it acceptable.

Thanks!

**Comment by mntmn** [comment]
@MishkinBerteig thanks, I finally had time to verify this. works well!

**Pull request merged**
